# Generated by Django 5.0.6 on 2024-06-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
