# Generated by Django 5.0.6 on 2024-06-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_game_genre_game_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genres',
        ),
    ]
